#!/bin/bash

[ -v V ] && set -x

set -eEu

: "${LIBPATH:="$(realpath "$(dirname "${0}")"/../lib/dyndns-updater)"}"
: "${SECRETFILE:="${HOME}/.keys/dyndns"}"

die() {
	for msg in "${@}"; do echo -e "${msg}"; done >&2
	exit 1
}
export -f die

for cmd in dig curl; do
	if ! command -v "${cmd}" &>/dev/null; then
		die "Command '${cmd}' is not found or not present in PATH, please install it and rerun this script"
	fi
done

get_dns_ipv4() {
	dig +short "${DYNDNS_HOST}"
}

set_dns_ipv4() {
#	local usr="${1}"
#	local pwd="${2}"
#	local nip="${3}"
	die	"This is the default callback to set DNS entry" \
		"And so .... This is an error."
}

get_wan_ipv4() {
	curl -m 5 -4 --silent https://ifconfig.co
}

if [ "$(basename "${0}")" == get-wan-ip ]; then
	get_wan_ipv4
	exit 0
fi

#shellcheck source=/dev/null
source "${SECRETFILE}" || {
	die "Could not source secret file: '${SECRETFILE}'"
}

if [ ! -v DYNDNS_PROVIDER ]; then
	die "Please set DYNDNSPROVIDER variable from env or secret file"
fi

#shellcheck source=/dev/null
source "${LIBPATH}/${DYNDNS_PROVIDER}" || {
	die "Failed to load helper for ${DYNDNS_PROVIDER}"
}

dns_ipv4=$(get_dns_ipv4)
wan_ipv4=$(get_wan_ipv4)

if [ "${dns_ipv4}" == "${wan_ipv4}" ]; then
	echo "Remote IP & current ip are matching, nothing to do"
	exit 0
fi

set_dns_ipv4 "${DYNDNS_USER}" "${DYNDNS_PASSWD}" "${wan_ipv4}"
