#!/bin/bash

[ -v V ] && set -x

set -eEu

: "${LIBPATH:=/usr/lib/update-dyndns}"
: "${SECRETFILE:="${HOME}/.keys/dyndns"}"

die() {
	for msg in "${@}"; do echo -e "${msg}"; done >&2
	exit 1
}
export -f die

for cmd in dig curl; do
	if ! command -v "${cmd}" &>/dev/null; then
		die "Command '${cmd}' is not found or not present in PATH, please install it and rerun this script"
	fi
done

#shellcheck source=/dev/null
source "${SECRETFILE}" || {
	die "Could not source secret file: '${SECRETFILE}'"
}

if [ ! -v DYNDNS_PROVIDER ]; then
	die "Please set DYNDNSPROVIDER variable from env or secret file"
fi

#shellcheck source=/dev/null
source "${LIBPATH}/${DYNDNS_PROVIDER}" || {
	die "Failed to load helper for ${DYNDNS_PROVIDER}"
}

default_get_dns_ipv4_callback() {
	dig +short "${DYNDNS_HOST}"
}

default_set_dns_ipv4_callback() {
#	local usr="${1}"
#	local pwd="${2}"
#	local nip="${3}"
	die	"This is the default callback to set DNS entry" \
		"And so .... This is an error."
}

default_get_wan_ipv4_callback() {
	curl -m 5 -4 --silent https://ifconfig.co
}

execute_callback() {
	local callback_name="${1}"
	shift
	if command -v "${callback_name}_callback" &>/dev/null; then
		"${callback_name}_callback" "${@}"
	else
		"default_${callback_name}_callback" "${@}"
	fi
}

dns_ipv4=$(execute_callback get_dns_ipv4)
wan_ipv4=$(execute_callback get_wan_ipv4)

if [ "${dns_ipv4}" == "${wan_ipv4}" ]; then
	echo "Remote IP & current ip are matching, nothing to do"
	exit 0
fi

execute_callback set_dns_ipv4 "${DYNDNS_USER}" "${DYNDNS_PASSWD}" "${wan_ipv4}"
