#!/bin/bash

set_dns_ipv4() {
	local usr="${1}"
	local pwd="${2}"
	local nip="${3}"
	curl -m 5 -L --location-trusted --user "${usr}:${pwd}" \
		"https://www.ovh.com/nic/update?system=dyndns&hostname=${DYNDNS_HOST}&myip=${nip}"
}
